apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: togglemaster
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpTZW5oYU1pY2h1cnVjYTEyM0B0b2dnbGVtYXN0ZXItYXV0aC1kYi5jd3JiZWVhdHFnc2IudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvYXV0aF9kYj9zc2xtb2RlPXJlcXVpcmU=
  MASTER_KEY: bWFzdGVyMTIz
---
apiVersion: v1
kind: Secret
metadata:
  name: flag-service-secret
  namespace: togglemaster
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpTZW5oYU1pY2h1cnVjYTEyM0B0b2dnbGVtYXN0ZXItZmxhZy1kYi5jd3JiZWVhdHFnc2IudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvZmxhZ19kYj9zc2xtb2RlPXJlcXVpcmU=
---
apiVersion: v1
kind: Secret
metadata:
  name: targeting-service-secret
  namespace: togglemaster
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpTZW5oYU1pY2h1cnVjYTEyM0B0b2dnbGVtYXN0ZXItdGFyZ2V0aW5nLWRiLmN3cmJlZWF0cWdzYi51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb206NTQzMi90YXJnZXRpbmdfZGI/c3NsbW9kZT1yZXF1aXJl
---
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
  namespace: togglemaster
type: Opaque
data:
  REDIS_URL: cmVkaXM6Ly90b2dnbGVtYXN0ZXItcmVkaXMucTdtd2J3LjAwMDEudXNlMS5jYWNoZS5hbWF6b25hd3MuY29tOjYzNzk=
  AWS_SQS_URL: aHR0cHM6Ly9zcXMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vNDg0MzM4Mjk2NjE4L3RvZ2dsZW1hc3Rlci1ldmVudHM=
  SERVICE_API_KEY: dGVtcA==
---
apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secret
  namespace: togglemaster
type: Opaque
data:
  AWS_SQS_URL: aHR0cHM6Ly9zcXMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vNDg0MzM4Mjk2NjE4L3RvZ2dsZW1hc3Rlci1ldmVudHM=
