apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: togglemaster
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/pcoutinhoo/togglemaster-gitops.git
    targetRevision: develop
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: togglemaster

  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: analytics-service
      namespace: togglemaster
      jsonPointers:
        - /spec/replicas

    - group: apps
      kind: Deployment
      name: evaluation-service
      namespace: togglemaster
      jsonPointers:
        - /spec/replicas

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
